# Generated by Django 3.2.3 on 2021-05-23 20:02

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tch_id', models.CharField(max_length=20)),
                ('tch_name', models.CharField(max_length=20)),
                ('tch_password', models.CharField(max_length=20)),
                ('tch_college', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('body', ckeditor.fields.RichTextField()),
                ('sheet_slug', models.SlugField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('week', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='student.week')),
            ],
        ),
    ]
